library(mosaic)
library(rgeos)
library(rgdal)
library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(tibble)
library(tidyverse)
library(magrittr)
library(aws.s3)
library(lubridate)
library(ggplot2)
library(ggmap)
library(RColorBrewer)
library(wesanderson)
library(GGally)
library(ranger)
library(caret)
library(funModeling)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
